import Head from 'next/head'

import styles from 'styles/Home.module.css'

export default function Complete() {
    return <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h2>Thank you.</h2>
            <h2>Registration Complete</h2>
        </main>
    </div>
}
