import {useEffect, useState} from "react";
import Head from 'next/head'
import Image from 'next/image'

import styles from 'styles/Home.module.css'
import Loading from 'components/Loading'
import {axios} from "utils/axios";
import config from "config";
import Link from "next/link";
import getIdToken from "utils/get_id_token";

export default function Home() {
    const [queryData, setQueryData] = useState(null)
    const getData = async () => {
        const id_token = getIdToken();
        const data = await axios({url: `${config.urls.api}associateChargingLocation`,  method: 'POST', body: {
                id_token,
                latitude: 59.911491,
                longitude: 10.757933
            }})
        setQueryData(data.data)
    }
    useEffect(() => {
        getData()
    }, [])

    return queryData ? <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h2>Thank you.</h2>
            <h2>Registration Complete</h2>
        </main>
    </div> : <Loading />
}
