import Head from 'next/head'
import config from "config";
import Link from "next/link";

import styles from 'styles/Home.module.css'

export default function ConnectedToEncode() {
    return <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h2>Successfully connected to ENode, now lets check your vehicle</h2>
            <Link href={config.urls.vehicleMatching} passHref legacyBehavior><button>Continue</button></Link>
            <Link href={config.urls.root} passHref legacyBehavior><button>Something went wrong</button></Link>
        </main>
    </div>
}
