import {useEffect, useState} from "react";
import Head from 'next/head'
import config from "config";
import Link from "next/link";

import styles from 'styles/Home.module.css'
import Loading from 'components/Loading'
import {axios} from "utils/axios";
import getIdToken from "utils/get_id_token";

export default function YourVehicle() {
    const getData = async () => {
        const id_token = getIdToken();
        await axios({url: `${config.urls.api}associateVehicle`, method: 'POST', body: {
                id_token
            }})
    }
    useEffect(() => {
        getData()
    }, [])

    return <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h2>Successfully connected to ENode, now lets check your vehicle</h2>
            <Link href={`/your_vehicle`} passHref legacyBehavior><button>Continue</button></Link>
            <Link href={`/`} passHref legacyBehavior><button>Something went wrong</button></Link>
        </main>
    </div>
}
