import {useEffect, useState} from "react";
import Head from 'next/head'

import styles from 'styles/Home.module.css'
import Loading from 'components/Loading'
import {axios} from "utils/axios";
import config from "config";
import Link from "next/link";
import getIdToken from "utils/get_id_token";

export default function Home() {
    const [queryData, setQueryData] = useState(null)
    const getData = async () => {
        const id_token = getIdToken();
        const data = await axios({url: `${config.urls.api}vehicleLocation`, body: {
                id_token
            }})
        setQueryData(data.data)
    }
    useEffect(() => {
        getData()
    }, [])

    return queryData ? <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h2>Your charging location is:</h2>
            <h4>Lat: {queryData.location.latitude}</h4>
            <h4>Long: {queryData.location.longitude}</h4>
            <div className="buttonContainer">
                <Link href={`/complete`} passHref legacyBehavior><button>Confirm</button></Link>
                <Link href={`/please_park_at_home`} passHref legacyBehavior><button>Retry</button></Link>
            </div>
        </main>
    </div> : <Loading />
}
